sudo: required

language: java
jdk:
  - openjdk8

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - docker --version

before_script:
  - cd secrets-management-service/

after_success:
  - mvn package dockerfile:build
  - mvn dockerfile:tag

cache:
  directories:
    - $HOME/.m2/repository/
