version: '3.6'
services:
  vault:
    image: vault
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_DEV_ROOT_TOKEN_ID=00000000-0000-0000-0000-000000000000
    cap_add:
      - IPC_LOCK
  secrets-management-service:
    image: bkhablenko/secrets-management-service
    environment:
      - JAVA_OPTS=-Xmx1024m
      - VAULT_HOST=vault
      - VAULT_TOKEN=00000000-0000-0000-0000-000000000000
    ports:
      - "8080:8080"
    depends_on:
      - vault
